### ISSUE TITLE
扫描自定义字体库失败

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#1]
1.02 & 1.00版本 扫描VCB字体完全包XZ失败

#####
正在读取字体信息...
65/765 8.50% Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre.py", line 1206, in <module>
    font_name = fontProgress(fontlist, font_name)
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre.py", line 617, in fontProgress
    if font_family[familyN].get((isItalic, isBold)) is not None:
KeyError: 'FZZhongDengXian-Z07 '

[已退出进程，代码为 1]

##咕咕咕

**Comment by DYY-Studio** [comment]
最初开发版本扫描XZ时没有发现问题，后来就没扫过了。
感谢反馈，之后会着手调查。

**Comment by DYY-Studio** [comment]
清楚了，是我偷懒没有把familyN的首尾空格去掉，而词典里的familyN这个key是去掉了首尾空格的
给我自己整笑了
