### ISSUE TITLE
拖动输入字体错误

### ISSUE THREAD

**Issue by DYY-Studio** [DYY-Studio/AddSubFontMKV_py#10]
该问题仅存在于Pre9-2f2，PyQt Beta版本因为删掉了这个功能所以一点问题都没有

```
Traceback (most recent call last):
  File "d:\Batch\ASFMKV_py1.02-pre9.py", line 2760, in <module>
    loadMain()
  File "d:\Batch\ASFMKV_py1.02-pre9.py", line 2679, in loadMain
    cFontSubset(font_info)
  File "d:\Batch\ASFMKV_py1.02-pre9.py", line 2345, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, [subp],
  File "d:\Batch\ASFMKV_py1.02-pre9.py", line 1852, in main
    assfont2, font_info = checkAssFont(fontlist, font_info)
  File "d:\Batch\ASFMKV_py1.02-pre9.py", line 1026, in checkAssFont
    font_path = font_name[ss][0]
KeyError: 'G-OTF Shin maru Go Pro M'
```

**Comment by DYY-Studio** [comment]
经排查发现是拖动输入后，本程序不再进行字幕名称大小写不统一转换，导致诸神字幕组**G-OTF Shin maru Go Pro M**字体名称与**G-OTF Shin Maru Go Pro M**无法匹配而报错

现已添加对应功能
