### ISSUE TITLE
fx15程序崩溃

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#24]
[文件链接](https://baleines.lanzoul.com/ibRsV0tx33dc)

分析字幕: "[KTXP&VCB-Studio] Plastic Memories [Preview11][Ma10p_1080p][x265_flac].Flsnow.ass" UTF-8-SIG
字幕所需字体
"冬青黑体简体中文 W3": 字符数[72]
字体输出路径: "E:\Downloads\[KTXP&VCB-Studio] Plastic Memories [Ma10p_1080p]\Previews\Fonts\[KTXP&VCB-Studio] Plastic Memories [Preview11][Ma10p_1080p][x265_flac].Flsnow"
[1/1] 正在子集化…… WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType
WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType
WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType
WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType
WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType

Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f5.py", line 3482, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f5.py", line 3396, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f5.py", line 2779, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f5.py", line 2274, in main
    assFontChange(multiAss[s][0], newfont_name, s, multiAss[s][1], multiAss[s][3], multiAss[s][2], multiAss[s][4],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f5.py", line 1615, in assFontChange
    if not newfont_name[nfnKey][1] is None:
KeyError: '冬青黑体简体中文 W6?1?1'

**Comment by DYY-Studio** [comment]
newfont_name变量的整个结构打算要换的，f5是临时的，只能说果然出问题了）
这几个月忙烂了，都不得空改

**Comment by Duan-rax** [comment]
hahaa,怎么有个没修好的提示
[文件](https://baleines.lanzoul.com/i6w8I0uxqvcd)
[10/10] 正在子集化……
字幕输出路径: "E:\Downloads\[KTXP&VCB-Studio] Plastic Memories [Ma10p_1080p]\subs"
字幕输出路径: "E:\Downloads\[KTXP&VCB-Studio] Plastic Memories [Ma10p_1080p]\subs"
没修好


Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16.py", line 3409, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16.py", line 3323, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16.py", line 2698, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16.py", line 2208, in main
    mkvr = ASFMKV(vpath, path.join(outdir[2], path.splitext(path.basename(vpath))[0] + '.mkv'),
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16.py", line 1664, in ASFMKV
    assfn = path.splitext(path.basename(s))[0]
  File "C:\Users\Duanp\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 242, in basename
    return split(p)[1]
  File "C:\Users\Duanp\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType


您要重新启动本程序吗？ [Y,N]?

**Comment by DYY-Studio** [comment]
pre16不是移掉了吗
当时就是debug的时候想看看是不是会出问题加的）

**Comment by DYY-Studio** [comment]
### 典中典
查出来了，是新的变量格式里用的是 (str, int, int)，而旧的匹配模式是 (str, str, str)
而我，漏改了这里

**Comment by Duan-rax** [comment]
[文件链接](https://baleines.lanzoul.com/i9ABz0w1maxe)

字体输出路径: "E:\Downloads\[Nekomoe kissaten&VCB-Studio] Kawaii dake ja Nai Shikimori-san [Ma10p_1080p]\Fonts\[Nekomoe kissaten&VCB-Studio] Kawaii dake ja Nai Shikimori-san [01][Ma10p_1080p][x265_flac_aac].Nekomoe kissaten"
[8/15] 正在子集化…… WARNING: Some CFF FDArray/FontDict keys were ignored upon compile: PaintType
[15/15] 正在子集化……
字幕输出路径: "E:\Downloads\[Nekomoe kissaten&VCB-Studio] Kawaii dake ja Nai Shikimori-san [Ma10p_1080p]\subs"
找不到字体
这很有可能是一个BUG，请及时反馈
请按任意键继续. . .


Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f1.py", line 3412, in <module>
    loadMain(True)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f1.py", line 3324, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f1.py", line 2699, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f1.py", line 2209, in main
    mkvr = ASFMKV(vpath, path.join(outdir[2], path.splitext(path.basename(vpath))[0] + '.mkv'),
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f1.py", line 1665, in ASFMKV
    assfn = path.splitext(path.basename(s))[0]
  File "C:\Users\Duanp\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 242, in basename
    return split(p)[1]
  File "C:\Users\Duanp\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by DYY-Studio** [comment]
我刚想改掉这里来着，你就成功试出来了）
现在没电脑改，我先分析下字幕…

**Comment by Duan-rax** [comment]
pre16-f2
大佬，这个报错的话，是我本地字体有什么问题吗
字体输出路径: "E:\Downloads\[Nekomoe kissaten&VCB-Studio] Hataraku Saibou Black [Ma10p_1080p]\Fonts\[Nekomoe kissaten&VCB-Studio] Hataraku Saibou Black [01][Ma10p_1080p][x265_flac_2aac].Nekomoe kissaten"
[6/6] 正在子集化……
字幕输出路径: "E:\Downloads\[Nekomoe kissaten&VCB-Studio] Hataraku Saibou Black [Ma10p_1080p]\subs"


Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f2.py", line 3416, in <module>
    loadMain(True)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f2.py", line 3328, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f2.py", line 2703, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre16f2.py", line 2211, in main
    asslangs=asslangs, asspaths=newasspath, fontpaths=list(set(list(newfont_name.values()))))
TypeError: unhashable type: 'list'

**Comment by DYY-Studio** [comment]
不是，我没试过mkvmerge那步，还是我的问题
主要是我这3G烂网小手机开远程太痛苦了
我一会处理

**Comment by DYY-Studio** [comment]
我做梦梦到出BUG，这下我要笑死了

**Comment by Duan-rax** [comment]
日有所思，夜有所梦。别着急，慢慢来。
