### ISSUE TITLE
转换字幕编码时报No such file or directory错误

### ISSUE THREAD

**Issue by honeyjuice** [DYY-Studio/AddSubFontMKV_py#25]
原以为是因为权限引起的问题，复制到D盘处理同样报错
版本为ASFMKV_pre13.py

```
Simple ASS/SSA to UTF-8-BOM Batch

字幕路径或字幕所在目录路径:Y:\Media\TV Shows\House of the Dragon\Season 01

搜索子目录: False
是否要将目标目录的子目录的字幕一起转换?
输入任意键(除空格)并回车进入到下一步
不输入任何值切换是否搜索子目录
e
[WinError 3] 系统找不到指定的路径。: ''
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E01 - The Heirs of the Dragon.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E02 - The Rogue Prince.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E03 - Second of His Name.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E04 - King of the Narrow Sea.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E05 - We Light the Way.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E06 - The Princess and the Queen.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E07 - Driftmark.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E08 - The Lord of the Tides.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E09 - The Green Council.utf8.ass'
[Errno 2] No such file or directory: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E10 - The Black Queen.utf8.ass'


Traceback (most recent call last):
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 3350, in <module>
    loadMain()
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 3343, in loadMain
    cTextCodingTranscode()
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 2994, in cTextCodingTranscode
    if not len(os.listdir(outPath)):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'Y:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles'


您要重新启动本程序吗？ [Y,N]?


```

```
Simple ASS/SSA to UTF-8-BOM Batch
字幕路径或字幕所在目录路径:D:\Media\TV Shows\House of the Dragon\Season 01

搜索子目录: False
是否要将目标目录的子目录的字幕一起转换?
输入任意键(除空格)并回车进入到下一步
不输入任何值切换是否搜索子目录
q
[WinError 3] 系统找不到指定的路径。: ''
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E01 - The Heirs of the Dragon.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E02 - The Rogue Prince.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E03 - Second of His Name.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E04 - King of the Narrow Sea.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E05 - We Light the Way.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E06 - The Princess and the Queen.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E07 - Driftmark.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E08 - The Lord of the Tides.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E09 - The Green Council.utf8.ass'
[Errno 2] No such file or directory: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles\\House of the Dragon - S01E10 - The Black Queen.utf8.ass'


Traceback (most recent call last):
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 3350, in <module>
    loadMain()
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 3343, in loadMain
    cTextCodingTranscode()
  File "D:\Program Files\MKVToolNix\ASFMKV_pre13.py", line 2994, in cTextCodingTranscode
    if not len(os.listdir(outPath)):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\Media\\TV Shows\\House of the Dragon\\Season 01\\UTF8-Subtitles'


您要重新启动本程序吗？ [Y,N]?
```

**Comment by DYY-Studio** [comment]
是我忘记创建目录了
已经在pre16搞定了，在Release里
