### ISSUE TITLE
子集封装内嵌ass问题

### ISSUE THREAD

**Issue by tb114514** [DYY-Studio/AddSubFontMKV_py#38]
[WARNING]
您输入的目录下只有字幕而无视频，每个字幕都将被当做单独对象处理
若是同一话有多个字幕，这话将会有多套子集化字体。
即便如此，您仍要继续吗？ [Y,N]?Y
正在尝试从字幕所在文件夹载入字体...
正在读取字体信息...
7/7 100.00% 【缓存】D:\Desktop\银魂

Traceback (most recent call last):
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 4153, in <module>
    loadMain(True)
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 4038, in loadMain
    cFontSubset(font_info)
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 3689, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, [subp],
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 2740, in main
    if path.splitext(s)[1][1:].lower() not in ['ass', 'ssa']:
  File "D:\Program Files\Python39\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by DYY-Studio** [comment]
似乎是代码本身的问题，待晚上确认后再作进一步答复。

**Comment by tb114514** [comment]
> 似乎是代码本身的问题，待晚上确认后再作进一步答复。


正在尝试从字幕所在文件夹载入字体...
正在读取字体信息...
7/7 100.00% 【缓存】D:\Desktop\银魂



Traceback (most recent call last):
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 4151, in <module>
    loadMain()
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 4038, in loadMain
    cFontSubset(font_info)
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 3689, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, [subp],
  File "D:\game\MKVToolNix\ASFMKV_pre21.py", line 2740, in main
    if path.splitext(s)[1][1:].lower() not in ['ass', 'ssa']:
  File "D:\Program Files\Python39\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple

单独子集化内嵌字体还是有这问题,子集化并封装视频没啥问题

**Comment by DYY-Studio** [comment]
抱歉，一直在忙，没空看这个问题。
我之前看错误就觉得应该是加功能的时候写错调用，但是我可能还要忙一周左右，抱歉。

**Comment by tb114514** [comment]
> 抱歉，一直在忙，没空看这个问题。 我之前看错误就觉得应该是加功能的时候写错调用，但是我可能还要忙一周左右，抱歉。


行

**Comment by DYY-Studio** [comment]
结果忙了三周

检查发现是这里没有对新的getFileList函数的返回值做相应的处理。

现已修复

**Comment by refined-fish** [comment]
> 结果忙了三周
> 
> 检查发现是这里没有对新的getFileList函数的返回值做相应的处理。
> 
> 现已修复

在pre22我也遇到了这个问题，以下是终端输出
```
正在尝试从字幕所在文件夹载入字体...
正在读取字体信息...
5/5 100.00% 【缓存】..][1080P][BDRip][HEVC-10bit][简繁外挂][FLAC][MKV]



Traceback (most recent call last):
  File "C:\Users\10140\Downloads\ASFMKV_pre22.py", line 4215, in <module>
    loadMain()
  File "C:\Users\10140\Downloads\ASFMKV_pre22.py", line 4102, in loadMain
    cFontSubset(font_info)
  File "C:\Users\10140\Downloads\ASFMKV_pre22.py", line 3753, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, [subp],
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10140\Downloads\ASFMKV_pre22.py", line 2804, in main
    if path.splitext(s)[1][1:].lower() not in ['ass', 'ssa']:
       ^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 232, in splitext
TypeError: expected str, bytes or os.PathLike object, not tuple
```

**Comment by DYY-Studio** [comment]
乐了，我再看看

还是那个问题，上次只修了一半属于是
