### ISSUE TITLE
 子集化出错

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#4]
第六集往后，前五集没报错，不知道是不是fn标签的问题，麻烦大佬看看，非常感谢
[视频：](https://www.dmhy.org/topics/view/604701_VCB-Studio_Seiren_10-bit_1080p_HEVC_BDRip_Fin.html#description-end)
[字幕：](https://baleines.lanzoul.com/iPVq507evc3i)
报错信息：
Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre7.py", line 2054, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre7.py", line 1984, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre7.py", line 1780, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre7.py", line 1424, in main
    else: newasspath.append(assFontChange(multiAss[s][0], newfont_name, s, multiAss[s][1], multiAss[s][3], multiAss[s][2], outdir[0], fn_lines=fn_lines))
  File "C:\Users\Duanp\Desktop\AddSubFontMKV_py-main\ASFMKV_py1.02-pre7.py", line 1158, in assFontChange
    fn_line = fn_line.replace(k, k.replace(fl[ti][k][0], newfont_name[fl[ti][k][0]][1]))
KeyError: ''

**Comment by DYY-Studio** [comment]
又是诸神字幕组，大草
确实是`fn`标签的问题
检查发现是诸神用了`fn`没接参数来重置字体为样式默认，这个倒是好办，根本不用处理，加个if就得了

我先给到Pre7-Fix1吧

**Comment by Duan-rax** [comment]
还有一个不知道算不算，好比现在字幕缺少一个字体，本地已经下载，如果处于工作目录，导入后会录入本次运行的缓存，如果在别的路径，在程序询问后手动导入，不会进入缓存，导致一次子集化过程中，多次要求导入同一字体

**Comment by DYY-Studio** [comment]
原本应该是设计成直接写到系统字体表里去的，按理来说应该不会出现重复询问
等我检查一下，有问题我改到pre8里面去

没有发现所述问题，确实是直接写到系统字体表里去了。我自己试了一下没有要求我重复导入。

**Comment by Duan-rax** [comment]
那看来是我系统权限问题，我的cmd默认管理模式打开了，麻烦了

**Comment by DYY-Studio** [comment]
我觉得不是那个问题……一会我再试试吧
但是管理权限的cmd……好像是不能直接拖入的吧）
（这里说的系统字体表是指程序内的词典，系统注册表的字体信息以及自定义目录的字体信息都会写到里面，它是全局性的）
