### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#44]
`C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f1.py:3833: SyntaxWarning: invalid escape sequence '\*'
  subonlyv = re.escape(subonlyv).replace('\*', '.*?')
请稍等，正在获取自定义文件夹中的字体
正在读取字体信息...
790/19095 4.14% f:\超级字体整合包 XZ\个人补
[ERROR] "f:\超级字体整合包 XZ\个人补\TT-新井行明.ttf": (<class 'fontTools.ttLib.TTLibFileIsCollectionError'>, TTLibFileIsCollectionError('specify a font number between 0 and 1 (inclusive)'), <traceback object at 0x0000020FFDCDE840>)
[TRY] 正在尝试使用TTC/OTC模式读取
[WARNING] 错误的字体扩展名"f:\超级字体整合包 XZ\个人补\TT-新井行明.ttf"
864/19095 4.52% f:\超级字体整合包 XZ\个人补                                too much 'OS/2' table data
886/19095 4.64% f:\超级字体整合包 XZ\个人补
[ERROR] "f:\超级字体整合包 XZ\个人补\华康娃娃体简W5.ttf": (<class 'fontTools.ttLib.TTLibFileIsCollectionError'>, TTLibFileIsCollectionError('specify a font number between 0 and 1 (inclusive)'), <traceback object at 0x0000020FFDC09D40>)
[TRY] 正在尝试使用TTC/OTC模式读取
[WARNING] 错误的字体扩展名"f:\超级字体整合包 XZ\个人补\华康娃娃体简W5.ttf"
1028/19095 5.38% f:\超级字体整合包 XZ\个人补                                too much 'OS/2' table data
2055/19095 10.76% f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文
[ERROR] "f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Ita-Tai Bold JIS & Arphic PIta-Tai Bold JIS.ttf": (<class 'fontTools.ttLib.TTLibFileIsCollectionError'>, TTLibFileIsCollectionError('specify a font number between 0 and 1 (inclusive)'), <traceback object at 0x0000020FFE086580>)
[TRY] 正在尝试使用TTC/OTC模式读取
[WARNING] 错误的字体扩展名"f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Ita-Tai Bold JIS & Arphic PIta-Tai Bold JIS.ttf"
2083/19095 10.91% f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文
[ERROR] "f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Singeitai Ultra JIS & Arphic PSingeitai Ultra JIS.ttf": (<class 'fontTools.ttLib.TTLibFileIsCollectionError'>, TTLibFileIsCollectionError('specify a font number between 0 and 1 (inclusive)'), <traceback object at 0x0000020FFE0A4B00>)
[TRY] 正在尝试使用TTC/OTC模式读取
[WARNING] 错误的字体扩展名"f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Singeitai Ultra JIS & Arphic PSingeitai Ultra JIS.ttf"
2086/19095 10.92% f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文
[ERROR] "f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Socho Medium JIS & Arphic PSocho Medium JIS.ttf": (<class 'fontTools.ttLib.TTLibFileIsCollectionError'>, TTLibFileIsCollectionError('specify a font number between 0 and 1 (inclusive)'), <traceback object at 0x0000020FFE0AA5C0>)
[TRY] 正在尝试使用TTC/OTC模式读取
[WARNING] 错误的字体扩展名"f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\日文\Arphic Socho Medium JIS & Arphic PSocho Medium JIS.ttf"
2119/19095 11.10% f:\超级字体整合包 XZ\完整包\Arphic（文鼎）\简体

Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f1.py", line 4411, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f1.py", line 4236, in loadMain
    font_info = fontProgress(font_list, [{}, {}, {}, {}, {}], f_priority)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f1.py", line 1353, in fontProgress
    encoding = lcidfil[platfID].get(langID, 'other')
               ~~~~~~~^^^^^^^^^
KeyError: 32


您要重新启动本程序吗？ [Y,N]?`

**Comment by DYY-Studio** [comment]
抱歉回复晚了。
按照微软和Apple的字体标准，PlatformID应当只有0-4。
报错显示PlatformID为32，这是不合法的。

对于其他的platformID，程序并没有做对应的处理。

我以后加个对应吧。

![image](https://github.com/user-attachments/assets/091f55aa-5b41-4bf1-9094-e4c394221f8f)

**Comment by Duan-rax** [comment]
老大快修🤤

**Comment by DYY-Studio** [comment]
dev分支那个修了，没试过，应该可以用，最近忙烂了😢

**Comment by Duan-rax** [comment]
"[VCB-Studio] Chiyu Mahou no Machigatta Tsukaikata [01][Ma10p_1080p][x265_flac].ass" - UTF-8-SIG
字幕所需字体
"方正大黑_GBK": 字符数[623]
"方正管峻楷书 简繁": 字符数[18]
"方正韵动粗黑_GBK": 字符数[152]
字体输出路径: "F:\[VCB-Studio] Chiyu Mahou no Machigatta Tsukaikata [Ma10p_1080p]\Fonts\[VCB-Studio] Chiyu Mahou no Machigatta Tsukaikata [01][Ma10p_1080p][x265_flac]"
[1/3] 正在子集化……方正大黑_GBK

[ERROR] (<class 'AttributeError'>, AttributeError('Subrs'), <traceback object at 0x00000195D3412680>)
[WARNING] 字体"方正大黑_GBK.OTF"子集化失败，将会保留完整字体


Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 2001, in assFontSubset
    subset.main(subsetarg)
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\subset\__init__.py", line 3813, in main
    subsetter.subset(font)
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\subset\__init__.py", line 3601, in subset
    self._prune_post_subset(font)
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\subset\__init__.py", line 3584, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\subset\cff.py", line 159, in prune_post_subset
    self.remove_unused_subroutines()
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\subset\cff.py", line 184, in remove_unused_subroutines
    self.cff.remove_unused_subroutines()
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\cffLib\__init__.py", line 324, in remove_unused_subroutines
    remove_unused_subroutines(self)
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\cffLib\transforms.py", line 461, in remove_unused_subroutines
    local_subrs = font.FDArray[0].Private.Subrs
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fontTools\cffLib\__init__.py", line 2472, in __getattr__
    raise AttributeError(name)
AttributeError: Subrs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 4482, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 4369, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 4016, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, [subp[1]],
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 3015, in main
    newfont_name = assFontSubset(assfont, fo, FFmuxer==2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Duanp\Desktop\sub\ASFMKV_pre25f2.py", line 2015, in assFontSubset
    newfont_name[si3, si[0], si[1]] = [crcnewf, subfontcrc]
                                       ^^^^^^^
UnboundLocalError: cannot access local variable 'crcnewf' where it is not associated with a value

**Comment by Duan-rax** [comment]
https://baleines.lanzoul.com/imlTy2kcy0xc
字幕文件

**Comment by DYY-Studio** [comment]
fontTools抛出的错误，似乎是字体缺失Subroutine？建议从方正官网重新下载一个`方正大黑_GBK`尝试一下。
我要晚点才能试了。

然后是我对`errorStop`的参数处理有问题。
**修了**

**无法复现，考虑`方正大黑_GBK.OTF`字体有误**
