### ISSUE TITLE
一个字体多名称时可能导致程序崩溃？

### ISSUE THREAD

**Issue by DYY-Studio** [DYY-Studio/AddSubFontMKV_py#6]
```
Traceback (most recent call last):
  File "d:\Batch\ASFMKVpy\ASFMKV_GUI-b1.py", line 2563, in subsetClicked
    eventW.callMain(1)
  File "d:\Batch\ASFMKVpy\ASFMKV_GUI-b1.py", line 2558, in callMain
    cFontSubset(work, _inpath, ui.sPathL.text().strip())
  File "d:\Batch\ASFMKVpy\ASFMKV_GUI-b1.py", line 2191, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k], mux=domux, outdir=_outdir, vpath=k, asslangs=sublang, noProgress=True)      
  File "d:\Batch\ASFMKVpy\ASFMKV_GUI-b1.py", line 1870, in main
    assFontChange(multiAss[s][0], newfont_name, s, multiAss[s][1], multiAss[s][3], multiAss[s][2],
  File "d:\Batch\ASFMKVpy\ASFMKV_GUI-b1.py", line 1247, in assFontChange
    fn_line = fn_line.replace(k, k.replace(fname, newfont_name[fname][1]))
KeyError: '方正准圆_GBK'
```

**Comment by DYY-Studio** [comment]
已修复，现在会将单个字体对应多个字体名称直接分成多条信息，每条一个名称了
